### ISSUE TITLE
Reset av Map

### ISSUE THREAD

**Issue by Arvid4245** [VilleOlof/MineGuessr#7]
Hade varit smidigt om det som i förra versionen resetade kartan när man går över till nästa gissning. Alltså att den centreras över Nirethia.

Tack

//Arvid

**Comment by VilleOlof** [comment]
This is already implemented (See: [SP](https://github.com/VilleOlof/MineGuessr/blob/bc8ca35193a4db2bd701aae05ac07eba7e1f984d/src/lib/Game.ts#L226C1-L226C27), [MP](https://github.com/VilleOlof/MineGuessr/blob/bc8ca35193a4db2bd701aae05ac07eba7e1f984d/src/lib/multiplayer/Components/Playing.svelte#L105))

I also tested this myself just now and it worked with no issues.

Any steps to reproduce this seemingly bug?

**Comment by Arvid4245** [comment]
If I go further to the next guess it doesn't reset, this can be an issue
when speedrunning.

I just tested it.

This is not a big issue but would be great if it was possible to fix.

Den tis 10 sep. 2024 kl 02:53 skrev Ville ***@***.***>:

**Comment by VilleOlof** [comment]
This cant happen, this hasnt happened for me or anyone else ive tested with. With no video and or better steps and details i will close this issue
